--- #YAML:1.0
name:               POE-Wheel-Sendfile
version:            0.0100
abstract:           Extend POE::Wheel::ReadWrite with sendfile
author:
    - Philip Gwyn <fil@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
